## One cell of the turn order.
##
## Follows the design doc's mockup: a framed portrait with a [DEN] – [weakness] – [ETH]
## strip under it. The cell whose turn it is grows, and carries the fighter's name above.
##
## The concealment rule: "rival's density and weakness aren't shown in timeline if they
## aren't in the encyclopaedia (yet)". An unknown rival therefore shows the `unknown`
## weakness icon and NO numbers — but keeps its strip, so the cell does not change size
## the moment the species becomes known mid-encounter.
##
## No `class_name`, on purpose: the global class cache is only regenerated by the editor
## and the game launches from the command line, so a new one would be missing and fail at
## load. The encounter UI preloads this instead.
extends VBoxContainer

const SIZE_IDLE := 72.0
const SIZE_ACTIVE := 104.0

const COLOR_DEN := Color(0.94, 0.62, 0.24)
const COLOR_ETH := Color(0.42, 0.82, 0.87)
const COLOR_FRAME_IDLE := Color(0.24, 0.24, 0.28)
const COLOR_FRAME_ACTIVE := Color(1, 1, 1)

## Cell background by side: the mockup gives player characters a tinted background and
## rivals a neutral dark one.
const COLOR_BG_PLAYER := Color(0.10, 0.24, 0.22)
const COLOR_BG_RIVAL := Color(0.06, 0.06, 0.08)

## Weakness icons for the TURN ORDER — a dedicated set. Every cell has one: the five
## energies, plus `none` (no weakness at this position this turn) and `unknown` (hidden,
## or a rival not yet in the encyclopaedia).
##
## Note these are NOT the energy icons used on ability buttons, which are a different set
## in `ui/weaknesses/` answering a different reading need.
const TL_DIR := "res://assets/sprites/ui/timeline/"
const WEAKNESS_ICONS := {
	GameEnums.Energy.HEAT: TL_DIR + "heat.png",
	GameEnums.Energy.FLUID: TL_DIR + "fluid.png",
	GameEnums.Energy.CRYSTAL: TL_DIR + "crystal.png",
	GameEnums.Energy.ARCANE: TL_DIR + "arcane.png",
	GameEnums.Energy.TOXIC: TL_DIR + "toxic.png",
}
const ICON_NONE := TL_DIR + "none.png"
const ICON_UNKNOWN := TL_DIR + "unknown.png"

var _name_label: Label
var _frame: PanelContainer
var _portrait: TextureRect
var _den_label: Label
var _eth_label: Label
var _weakness_icon: TextureRect


func _init() -> void:
	alignment = BoxContainer.ALIGNMENT_CENTER
	add_theme_constant_override("separation", 2)

	_name_label = Label.new()
	_name_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_name_label.add_theme_font_size_override("font_size", 13)
	add_child(_name_label)

	_frame = PanelContainer.new()
	_frame.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	_portrait = TextureRect.new()
	_portrait.stretch_mode = TextureRect.STRETCH_SCALE
	# ESSENTIAL. Without it a TextureRect's minimum size is the source texture's own — 800
	# pixels and up — and `custom_minimum_size` does not cap that, because it is a floor
	# and not a ceiling. The cell would take the whole screen.
	_portrait.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	_frame.add_child(_portrait)
	add_child(_frame)

	var stats := HBoxContainer.new()
	stats.alignment = BoxContainer.ALIGNMENT_CENTER
	stats.add_theme_constant_override("separation", 2)
	_den_label = _make_pill(COLOR_DEN)
	stats.add_child(_den_label)

	# The weakness is ALWAYS an icon badge, never absent — one of the five energies,
	# `none`, or `unknown`.
	var badge := Control.new()
	badge.custom_minimum_size = Vector2(28, 28)
	_weakness_icon = TextureRect.new()
	_weakness_icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	_weakness_icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	_weakness_icon.set_anchors_preset(Control.PRESET_FULL_RECT)
	badge.add_child(_weakness_icon)
	stats.add_child(badge)

	_eth_label = _make_pill(COLOR_ETH)
	stats.add_child(_eth_label)
	add_child(stats)


func _make_pill(color: Color) -> Label:
	var l := Label.new()
	l.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	l.custom_minimum_size = Vector2(38, 18)
	l.add_theme_font_size_override("font_size", 12)
	l.add_theme_color_override("font_color", Color(0.08, 0.08, 0.1))
	var box := StyleBoxFlat.new()
	box.bg_color = color
	box.set_corner_radius_all(9)
	box.content_margin_left = 4
	box.content_margin_right = 4
	l.add_theme_stylebox_override("normal", box)
	return l


## Fills the cell in. `known` means the species is in the encyclopaedia; `active` means it
## is this fighter's turn.
##
## `rank` is only set in the debug view, where it labels EVERY cell "2. ravbak". In game
## only the active cell carries a name, as in the mockup — but testing needs the whole
## order readable at a glance.
func setup(
	fighter: EncounterFighter, known: bool, active: bool, weakness: GameEnums.Energy, rank: int = 0
) -> void:
	var side := SIZE_ACTIVE if active else SIZE_IDLE
	_portrait.custom_minimum_size = Vector2(side, side)
	_portrait.texture = _portrait_texture(fighter)
	_portrait.modulate = Color(1, 1, 1) if not fighter.is_dissolved() else Color(0.35, 0.35, 0.4)

	var frame_box := StyleBoxFlat.new()
	# Side is legible at a glance from the background alone, independently of which cell is
	# active — that one is marked by being larger with a white border.
	frame_box.bg_color = COLOR_BG_PLAYER if fighter.is_player else COLOR_BG_RIVAL
	frame_box.border_color = COLOR_FRAME_ACTIVE if active else COLOR_FRAME_IDLE
	frame_box.set_border_width_all(3 if active else 2)
	frame_box.set_corner_radius_all(4)
	_frame.add_theme_stylebox_override("panel", frame_box)

	if rank > 0:
		_name_label.text = "%d. %s" % [rank, fighter.display_name()]
		_name_label.visible = true
	else:
		_name_label.text = fighter.display_name() if active else ""
		_name_label.visible = active

	# A player's numbers are always readable; a rival's depend on the encyclopaedia. The
	# badges stay, empty, so that the cell does not shift when they appear.
	var show_numbers := fighter.is_player or known
	_den_label.text = str(fighter.den) if show_numbers else ""
	_eth_label.text = str(fighter.eth) if show_numbers else ""

	# `unknown` when the weakness is hidden (Anodyne Excess) OR the rival is not in the
	# encyclopaedia yet; otherwise the energy's icon, or `none` when this position exposes
	# no weakness at all this turn.
	var show_weakness := (fighter.is_player or known) and not fighter.weakness_hidden
	if not show_weakness:
		_weakness_icon.texture = load(ICON_UNKNOWN)
	elif WEAKNESS_ICONS.has(weakness):
		_weakness_icon.texture = load(WEAKNESS_ICONS[weakness])
	else:
		_weakness_icon.texture = load(ICON_NONE)  # no weakness at this position this turn


## A square portrait cropped from the TOP of the artwork, where the head is, rather than
## the whole piece squashed into a square.
func _portrait_texture(fighter: EncounterFighter) -> Texture2D:
	var path := "res://assets/sprites/spirimonsters/%s.png" % fighter.species_id()
	if not ResourceLoader.exists(path):
		return null
	var src: Texture2D = load(path)
	var w := src.get_width()
	var h := src.get_height()
	var side: int = mini(w, h)
	var atlas := AtlasTexture.new()
	atlas.atlas = src
	atlas.region = Rect2((w - side) / 2.0, 0, side, side)
	return atlas
