## Générateur : export Notion → ressources .tres typées + clés de traduction.
##
## Honnore la décision d'archi : les données ne sont JAMAIS saisies à la main dans
## l'éditeur. Ce script lit l'export HTML/CSV de Notion (situé hors du projet Godot,
## dans `../doc notion/`) et émet :
##   - res://data/abilities/<slug>.tres   (AbilityData ou TalentData)
##   - res://data/species/<slug>.tres     (SpeciesData)
##   - res://data/objects/<slug>.tres     (ObjectData)
##   - les clés SPECIES_*/ABILITY_*/TALENT_*/OBJECT_* dans translations/en.po + fr.po
##     (dans un bloc « GENERATED » regénéré à chaque exécution).
##
## Exécution (depuis `proj godot/`) :
##   /Applications/Godot.app/Contents/MacOS/Godot --headless --script res://tools/notion_to_tres.gd
##
## Idempotent : réécrit les .tres et remplace le bloc généré des .po.
extends SceneTree

const ABILITIES_OUT := "res://data/abilities/"
const SPECIES_OUT := "res://data/species/"
const OBJECTS_OUT := "res://data/objects/"

## Effet de chaque objet, mappé par SLUG et non déduit de la prose : [enum
## GameEnums.ObjectEffect] a été dérivé de cette liste même (7 objets, 7 effets), et
## inférer FLEE_ENCOUNTER de « allows to Run away from an encounter » serait fragile pour
## rien. Les slugs coïncident avec ceux de la propriété « Potential Loot » des espèces.
##
## « costume » est délibérément ABSENT : la doc dit « the costume name indicates which
## spirimonster – e.g. fopin costume », donc il y a un costume PAR espèce, et l'espèce
## évitée est « specified in object description ». Ni la liste ni aucune base Notion ne
## les énumère → rien à générer tant que ces données n'existent pas.
const OBJECT_EFFECTS := {
	"notice": GameEnums.ObjectEffect.NONE,
	"rune_stone": GameEnums.ObjectEffect.HEAL_DEN,
	"smoke_bomb": GameEnums.ObjectEffect.FLEE_ENCOUNTER,
	"spade": GameEnums.ObjectEffect.DIG,
	"tea_drop": GameEnums.ObjectEffect.CURE_POISON,
	"torment_veil": GameEnums.ObjectEffect.AVOID_PURSUIT,
}

## Durées explicitement chiffrées par la doc (en déplacements du joueur).
const OBJECT_DURATIONS := {"torment_veil": 15}
const PO_EN := "res://translations/en.po"
const PO_FR := "res://translations/fr.po"

const ABILITY_FX_OUT := "res://scripts/encounter/effects/abilities/"

const GEN_START := "# >>> GENERATED BY notion_to_tres.gd — NE PAS ÉDITER (regénéré à chaque run)"
const GEN_END := "# <<< END GENERATED"

# Marqueur de stub : si la 1re ligne d'un script d'effet le porte, le stub est
# considéré non implémenté et peut être régénéré ; sinon (implémenté), on n'y touche pas.
const STUB_MARKER := "# @generated-stub notion_to_tres.gd"

# Entrées de traduction collectées au fil de la génération.
# Chaque entrée : { "key": String, "en": String, "fr": String, "fr_todo": bool }.
var _po_entries: Array[Dictionary] = []
var _seen_keys: Dictionary = {}

# Relations dérivées du CSV des capacités, réutilisées pour les espèces.
var _talent_by_species: Dictionary = {}        # species_slug -> talent_slug
var _origin_abilities_by_species: Dictionary = {}  # species_slug -> Array[StringName]

# Pages HTML des capacités, indexées par slug (mécanique + description encyclopédie).
var _ability_pages: Dictionary = {}            # slug -> chemin .html
var _stubs_written := 0


func _initialize() -> void:
	var notion := _find_notion_root()
	if notion == "":
		push_error("[gen] Export Notion introuvable sous '../doc notion/'.")
		quit(1)
		return
	print("[gen] Racine Notion : %s" % notion)

	var csv_path := _find_abilities_csv(notion)
	var species_dir := notion.path_join("Private & Shared/Spiritology/Story + Characters/Possible Encounters")

	_index_ability_pages(notion)
	var n_abilities := _generate_abilities(csv_path)
	# AVANT les espèces : la passe « Potential Loot » référence les mêmes objets, et c'est
	# ici qu'on tient leur nom FR (la relation de loot, elle, n'a que le nom EN).
	var n_objects := _generate_objects(notion)
	var n_species := _generate_species(species_dir)
	_write_po()

	print("[gen] Terminé : %d capacités/talents, %d espèces, %d objets, %d clés de trad, %d stubs d'effet créés." % [
		n_abilities, n_species, n_objects, _po_entries.size(), _stubs_written])
	quit(0)


# --------------------------------------------------------------------------
# Objets (section « Objects + Inventory » de la page Game Design)
# --------------------------------------------------------------------------

## Génère les [ObjectData]. Contrairement aux espèces et aux capacités, les objets ne sont
## PAS une base de données Notion : ils sont décrits en liste à puces dans la page « Game
## Design », section « Objects + Inventory », sous la forme régulière
##   <strong>Nom EN</strong> <mark>(FR nom fr)</mark> – description
## suivie éventuellement d'un bloc de note imbriqué (ignoré : ce n'est pas la description).
func _generate_objects(notion: String) -> int:
	var page := _find_game_design_page(notion)
	if page == "":
		push_warning("[gen] page « Game Design » introuvable : aucun objet généré.")
		return 0
	var body := _body_of(page)
	var start := body.find("Objects + Inventory")
	if start < 0:
		push_warning("[gen] section « Objects + Inventory » introuvable : aucun objet généré.")
		return 0
	# La section suivante (« Dialogues ») borne la liste.
	var stop := body.find("Dialogues", start)
	var seg := body.substr(start, (stop - start) if stop > start else 4000)

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OBJECTS_OUT))
	var li_re := RegEx.create_from_string("(?s)<li[^>]*>(.*?)</li>")
	var strong_re := RegEx.create_from_string("(?s)<strong>(.*?)</strong>")
	var fr_re := RegEx.create_from_string("(?s)\\(FR\\s*(.*?)\\)")
	var count := 0
	for m in li_re.search_all(seg):
		var li := m.get_string(1)
		# Couper avant la note imbriquée : sans ça, _strip_tags la recolle à la description.
		var div := li.find("<div")
		var head := li.substr(0, div) if div >= 0 else li
		var sm := strong_re.search(head)
		if sm == null:
			continue
		var name_en := _strip_tags(sm.get_string(1))
		var slug := _slugify(name_en)
		if slug == "":
			continue
		if not OBJECT_EFFECTS.has(slug):
			# Costume (par espèce, non énumérable) ou objet ajouté à la doc depuis : on
			# préfère le signaler que de deviner un effet.
			push_warning("[gen] objet « %s » sans effet connu → ignoré (cf. OBJECT_EFFECTS)." % slug)
			continue
		var flat := _strip_tags(head)
		var fr_m := fr_re.search(flat)
		var name_fr := fr_m.get_string(1).strip_edges() if fr_m else ""
		_save_object(slug)
		_add_translation("OBJECT_%s_NAME" % _key_token(slug), name_en, name_fr)
		_add_translation("OBJECT_%s_DESC" % _key_token(slug), _object_desc(flat), "")
		count += 1
	return count

## Description = ce qui suit le tiret cadratin, la parenthèse « (FR …) » retirée.
func _object_desc(flat: String) -> String:
	var i := flat.find("–")
	if i < 0:
		i = flat.find("-")
	return flat.substr(i + 1).strip_edges() if i >= 0 else ""

func _save_object(slug: String) -> void:
	var o := ObjectData.new()
	o.id = StringName(slug)
	o.effect = OBJECT_EFFECTS[slug]
	o.duration_moves = OBJECT_DURATIONS.get(slug, 0)
	# magnitude laissée à 0 : la doc écrit « X % » / « Y DEN » — ce sont littéralement des
	# placeholders surlignés dans Notion, pas des chiffres. À renseigner quand ils existeront.
	var err := ResourceSaver.save(o, OBJECTS_OUT + slug + ".tres")
	if err != OK:
		push_error("[gen] écriture objet échouée : %s (%d)" % [slug, err])

## Localise la page « Game Design » (son suffixe de hash change à chaque export Notion).
func _find_game_design_page(notion: String) -> String:
	var folder := notion.path_join("Private & Shared/Spiritology")
	var dir := DirAccess.open(folder)
	if dir == null:
		return ""
	for f in dir.get_files():
		if f.begins_with("Game Design ") and f.ends_with(".html"):
			return folder.path_join(f)
	return ""


## Indexe les pages HTML des capacités (dossier « List of Abilities ») par slug.
func _index_ability_pages(notion: String) -> void:
	var folder := notion.path_join("Private & Shared/Spiritology/Game Design/Abilities + Talents/List of Abilities")
	var dir := DirAccess.open(folder)
	if dir == null:
		push_warning("[gen] dossier des pages de capacités introuvable : %s" % folder)
		return
	var re := RegEx.create_from_string(" [0-9a-f]{32}\\.html$")
	for f in dir.get_files():
		if not f.ends_with(".html"):
			continue
		var name := re.sub(f, "", true)
		var slug := _slugify(name)
		if slug != "":
			_ability_pages[slug] = folder.path_join(f)


# --------------------------------------------------------------------------
# Découverte des chemins source (hors res://)
# --------------------------------------------------------------------------

## Localise le dossier ExportBlock-* sous `<racine projet>/../doc notion/`.
func _find_notion_root() -> String:
	var proj_root := ProjectSettings.globalize_path("res://").trim_suffix("/")
	var spirit_root := proj_root.get_base_dir()
	var docs := spirit_root.path_join("doc notion")
	var dir := DirAccess.open(docs)
	if dir == null:
		return ""
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and name.begins_with("ExportBlock-"):
			dir.list_dir_end()
			return docs.path_join(name)
		name = dir.get_next()
	dir.list_dir_end()
	return ""


func _find_abilities_csv(notion: String) -> String:
	var folder := notion.path_join("Private & Shared/Spiritology/Game Design/Abilities + Talents")
	var dir := DirAccess.open(folder)
	if dir == null:
		return ""
	for f in dir.get_files():
		if f.begins_with("List of Abilities") and f.ends_with(".csv"):
			return folder.path_join(f)
	return ""


# --------------------------------------------------------------------------
# Capacités & talents (depuis le CSV)
# --------------------------------------------------------------------------

func _generate_abilities(csv_path: String) -> int:
	var file := FileAccess.open(csv_path, FileAccess.READ)
	if file == null:
		push_error("[gen] CSV illisible : %s" % csv_path)
		return 0

	var header := file.get_csv_line()  # Name,Cost,Damage,Energy,FR,Origin Species,Single-Use,Tags,Type
	var count := 0
	while not file.eof_reached():
		var row := file.get_csv_line()
		if row.size() < 9 or row[0].strip_edges() == "":
			continue
		var raw_name := row[0].strip_edges()
		var cost_s := row[1].strip_edges()
		var damage_s := row[2].strip_edges()
		var energy_s := row[3].strip_edges()
		var fr := row[4].strip_edges()
		var origin_s := _link_label(row[5])
		var single_use := row[6].strip_edges().to_lower() == "yes"
		var tags_s := row[7].strip_edges()
		var type_s := row[8].strip_edges()

		var display_name := raw_name.lstrip("[").rstrip("]")
		var slug := _slugify(display_name)
		if slug == "":
			continue
		var origin_slug := _slugify(origin_s)

		var type := _parse_type(type_s)
		if type == GameEnums.AbilityType.TALENT:
			_save_talent(slug, origin_slug, tags_s)
			if origin_slug != "":
				_talent_by_species[origin_slug] = slug
			_add_translation("TALENT_%s_NAME" % _key_token(slug), display_name, fr)
		else:
			_save_ability(slug, type, origin_slug, energy_s, cost_s, damage_s, single_use, tags_s)
			if origin_slug != "":
				var arr: Array = _origin_abilities_by_species.get(origin_slug, [])
				arr.append(StringName(slug))
				_origin_abilities_by_species[origin_slug] = arr
			_add_translation("ABILITY_%s_NAME" % _key_token(slug), display_name, fr)
			# Mécanique + description encyclopédie depuis la page HTML de la capacité.
			var page := _read_ability_page(slug)
			if page["desc_fr"] != "" or page["desc_en"] != "":
				_add_translation("ABILITY_%s_DESC" % _key_token(slug), page["desc_en"], page["desc_fr"])
			_write_effect_stub(slug, display_name, type_s, origin_slug, energy_s,
				cost_s, damage_s, single_use, tags_s, page["mechanic"])
		count += 1
	return count


## Lit la page HTML d'une capacité : { mechanic, desc_fr, desc_en }.
## `mechanic` = spec de design (corps de page) ; `desc_*` = note encyclopédie joueur.
func _read_ability_page(slug: String) -> Dictionary:
	var result := {"mechanic": "", "desc_fr": "", "desc_en": ""}
	if not _ability_pages.has(slug):
		return result
	var body := _body_of(_ability_pages[slug])
	# Le corps de page suit la table de propriétés.
	var parts := body.split("</table>", false)
	var page_body: String = parts[parts.size() - 1] if parts.size() > 0 else body
	var text := _html_to_text(page_body)
	# Retirer les commentaires Notion (« Page comments … »).
	var cut := RegEx.create_from_string("(?i)\\bpage comments\\b")
	var mc := cut.search(text)
	if mc:
		text = text.substr(0, mc.get_start())
	# Séparer une éventuelle note encyclopédie (« note Fr pour encyclopédie : … »).
	var note_re := RegEx.create_from_string("(?is)\\bnote\\s+(fr|en)[^:\\n]*:\\s*")
	var nm := note_re.search(text)
	if nm:
		var lang := nm.get_string(1).to_lower()
		var note := text.substr(nm.get_end()).strip_edges()
		text = text.substr(0, nm.get_start())
		if lang == "fr":
			result["desc_fr"] = note
		else:
			result["desc_en"] = note
	result["mechanic"] = text.strip_edges()
	return result


## Écrit le stub de script d'effet d'une capacité, SAUF s'il existe déjà et qu'il a
## été implémenté à la main (absence du marqueur de stub en tête).
func _write_effect_stub(slug: String, name: String, type_s: String, origin: String,
		energy_s: String, cost_s: String, damage_s: String, single_use: bool,
		tags_s: String, mechanic: String) -> void:
	var path := ABILITY_FX_OUT + slug + ".gd"
	if FileAccess.file_exists(path):
		var head := FileAccess.get_file_as_string(path)
		if not head.begins_with(STUB_MARKER):
			return  # implémenté à la main : on ne touche pas
	var meta := "%s · origine %s · %s · coût %s · dégâts %s%s" % [
		type_s,
		origin if origin != "" else "—",
		energy_s if energy_s != "" else "—",
		cost_s if cost_s != "" else "—",
		damage_s if damage_s != "" else "—",
		" · usage unique" if single_use else "",
	]
	var lines := PackedStringArray()
	lines.append(STUB_MARKER)
	lines.append("## %s — %s" % [name, meta])
	if tags_s != "":
		lines.append("## Tags : %s" % tags_s)
	lines.append("##")
	if mechanic != "":
		lines.append("## MÉCANIQUE (Notion) :")
		for ml in _wrap(mechanic, 88):
			lines.append("##   %s" % ml)
	else:
		lines.append("## MÉCANIQUE : non documentée dans Notion (à définir).")
	lines.append("extends AbilityScript")
	lines.append("")
	lines.append("")
	lines.append("func execute(ctx: EncounterContext) -> void:")
	lines.append("\t# TODO: implémenter la mécanique unique ci-dessus, puis retirer la ligne")
	lines.append("\t# « %s » en tête pour figer ce script." % STUB_MARKER.substr(2))
	lines.append("\t# Par défaut : effets génériques dérivés des tags.")
	lines.append("\tsuper.execute(ctx)")
	lines.append("")
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		push_warning("[gen] écriture stub impossible : %s" % path)
		return
	f.store_string("\n".join(lines))
	_stubs_written += 1


## Découpe un texte en lignes d'au plus `width` caractères (coupe aux espaces).
func _wrap(text: String, width: int) -> PackedStringArray:
	var out := PackedStringArray()
	for paragraph in text.split("\n", false):
		var line := ""
		for word in paragraph.split(" ", false):
			if line == "":
				line = word
			elif line.length() + 1 + word.length() <= width:
				line += " " + word
			else:
				out.append(line)
				line = word
		if line != "":
			out.append(line)
	return out


func _save_ability(slug: String, type: int, origin: String, energy_s: String,
		cost_s: String, damage_s: String, single_use: bool, tags_s: String) -> void:
	var a := AbilityData.new()
	a.id = StringName(slug)
	a.type = type
	a.origin_species = StringName(origin)
	a.energy = _parse_energy(energy_s)
	a.cost = _parse_cost(cost_s)
	a.base_damage = _parse_damage(damage_s)
	a.single_use = single_use
	a.tags = _split_tags(tags_s)
	var err := ResourceSaver.save(a, ABILITIES_OUT + slug + ".tres")
	if err != OK:
		push_warning("[gen] échec sauvegarde capacité %s (err %d)" % [slug, err])


func _save_talent(slug: String, owner: String, tags_s: String) -> void:
	var t := TalentData.new()
	t.id = StringName(slug)
	t.owner_species = StringName(owner)
	t.tags = _split_tags(tags_s)
	var err := ResourceSaver.save(t, ABILITIES_OUT + slug + ".tres")
	if err != OK:
		push_warning("[gen] échec sauvegarde talent %s (err %d)" % [slug, err])


# --------------------------------------------------------------------------
# Espèces (depuis les fiches HTML)
# --------------------------------------------------------------------------

func _generate_species(dir_path: String) -> int:
	var dir := DirAccess.open(dir_path)
	if dir == null:
		push_error("[gen] dossier espèces introuvable : %s" % dir_path)
		return 0
	var count := 0
	for f in dir.get_files():
		if not f.ends_with(".html"):
			continue
		if f.begins_with("Spirimonster Species"):
			continue  # page d'index, pas une espèce
		var slug := _species_slug_from_filename(f)
		if slug == "":
			continue
		var body := _body_of(dir_path.path_join(f))
		_save_species(slug, body)
		_add_translation("SPECIES_%s_NAME" % _key_token(slug), slug, slug)  # nom commun, non traduit
		count += 1
	return count


func _save_species(slug: String, body: String) -> void:
	var s := SpeciesData.new()
	s.id = StringName(slug)
	s.spiricosm = _parse_spiricosm(_select_value(_cell(body, "Origin")))
	s.weakness_first = _parse_energy(_select_value(_cell(body, "Weakness (first)")))
	s.weakness_middle = _parse_energy(_select_value(_cell(body, "Weakness (in-between)")))
	s.weakness_last = _parse_energy(_select_value(_cell(body, "Weakness (last)")))

	# Talker : propriété nombre « 30% » → probabilité normalisée 0.30 (cellule vide → 0.0).
	s.talker_chance = _percent_to_unit(_cell(body, "Talker (def. chance of init.)"))
	# « Can join … » : relation vers un/des groupes de Special Encounters. Non vide → l'espèce
	# peut rejoindre le duo (bool ; le détail des groupes reste dans Notion pour l'instant).
	s.can_join = not _anchor_texts(_cell(body, "Can join")).is_empty()

	# Talent + capacités d'origine viennent du CSV (source de vérité des relations).
	s.talent = StringName(_talent_by_species.get(slug, ""))
	var origin_arr: Array[StringName] = []
	for x in _origin_abilities_by_species.get(slug, []):
		origin_arr.append(x)
	s.origin_abilities = origin_arr

	# « Also uses » : liens dans la fiche.
	s.also_used_abilities = _slugs_from_links(_cell(body, "also uses"))

	# Déblocages d'encyclopédie : bloc « Abilities unlock » (1st / 2nd / Extreme).
	var unlock := _section_after(body, "Abilities unlock", 2500)
	var enc: Array[StringName] = []
	var first := _slug_of_anchor_after(unlock, "1st:")
	var second := _slug_of_anchor_after(unlock, "2nd:")
	if first != "":
		enc.append(StringName(first))
	if second != "":
		enc.append(StringName(second))
	s.encyclopaedia_abilities = enc
	s.forlorn_ability = StringName(_slug_of_anchor_after(unlock, "Extreme:"))

	# Loot : tags multi-sélection renvoyant aux objets. Les clés de traduction appartiennent
	# à la passe objets (_generate_objects), qui tourne avant et tient le nom FR : émettre
	# ITEM_*_NAME ici produisait des clés que personne ne lit — ObjectData.name_key()
	# cherche OBJECT_*_NAME.
	var loot: Array[StringName] = []
	for item_name in _select_values(_cell(body, "Potential Loot")):
		var item_slug := _slugify(item_name)
		if item_slug == "":
			continue
		loot.append(StringName(item_slug))
		if not FileAccess.file_exists(OBJECTS_OUT + item_slug + ".tres"):
			push_warning("[gen] loot « %s » (espèce %s) sans ObjectData généré." % [item_slug, slug])
	s.loot = loot

	# Sprite récupéré du proto Unity, par convention de nommage. Chemin String
	# (pas Texture2D) pour ne pas tirer la texture en RAM au chargement du .tres.
	var sprite_path := "res://assets/sprites/spirimonsters/%s.png" % slug
	if FileAccess.file_exists(sprite_path):
		s.sprite_idle = sprite_path

	var err := ResourceSaver.save(s, SPECIES_OUT + slug + ".tres")
	if err != OK:
		push_warning("[gen] échec sauvegarde espèce %s (err %d)" % [slug, err])


# --------------------------------------------------------------------------
# Parsing HTML (helpers)
# --------------------------------------------------------------------------

## Renvoie le corps de page (après le </style>).
func _body_of(path: String) -> String:
	var html := FileAccess.get_file_as_string(path)
	var i := html.find("</style>")
	return html.substr(i + 8) if i >= 0 else html

## Contenu HTML brut du <td> de la première property-row dont le <th> contient `label`.
func _cell(body: String, label: String) -> String:
	var i := body.find(label)
	if i < 0:
		return ""
	var td := body.find("<td", i)
	if td < 0:
		return ""
	var gt := body.find(">", td)
	var end := body.find("</td>", gt)
	if gt < 0 or end < 0:
		return ""
	return body.substr(gt + 1, end - gt - 1)

## Convertit une cellule de pourcentage Notion (ex. « 30% ») en probabilité [0.0, 1.0].
## Cellule vide ou non numérique → 0.0.
func _percent_to_unit(cell: String) -> float:
	var txt := _strip_tags(cell).strip_edges().replace("%", "").strip_edges()
	if txt == "" or not txt.is_valid_float():
		return 0.0
	return clampf(txt.to_float() / 100.0, 0.0, 1.0)

## Premier texte de <span class="selected-value …"> d'une cellule (champ select simple).
func _select_value(cell: String) -> String:
	var vals := _select_values(cell)
	return vals[0] if vals.size() > 0 else ""

## Tous les textes de <span class="selected-value …"> (champ multi-select).
func _select_values(cell: String) -> PackedStringArray:
	var out := PackedStringArray()
	var re := RegEx.create_from_string("<span class=\"selected-value[^\"]*\">(.*?)</span>")
	for m in re.search_all(cell):
		out.append(_strip_tags(m.get_string(1)))
	return out

## Textes de tous les <a>…</a> d'une cellule.
func _anchor_texts(cell: String) -> PackedStringArray:
	var out := PackedStringArray()
	var re := RegEx.create_from_string("<a[^>]*>(.*?)</a>")
	for m in re.search_all(cell):
		out.append(_strip_tags(m.get_string(1)))
	return out

## Convertit les liens d'une cellule en slugs d'identifiants.
func _slugs_from_links(cell: String) -> Array[StringName]:
	var out: Array[StringName] = []
	for t in _anchor_texts(cell):
		var slug := _slugify(t)
		if slug != "":
			out.append(StringName(slug))
	return out

## Segment de `length` caractères démarrant à la première occurrence de `marker`.
func _section_after(body: String, marker: String, length: int) -> String:
	var i := body.find(marker)
	return body.substr(i, length) if i >= 0 else ""

## Slug du premier <a> rencontré après le libellé `label` dans un segment.
func _slug_of_anchor_after(seg: String, label: String) -> String:
	var i := seg.find(label)
	if i < 0:
		return ""
	var a := seg.find("<a", i)
	if a < 0:
		return ""
	var gt := seg.find(">", a)
	var end := seg.find("</a>", gt)
	if gt < 0 or end < 0:
		return ""
	return _slugify(_strip_tags(seg.substr(gt + 1, end - gt - 1)))

## Label affiché d'un lien CSV « nom (../chemin.html) » → « nom ».
func _link_label(raw: String) -> String:
	var s := raw.strip_edges()
	var p := s.find(" (")
	return s.substr(0, p).strip_edges() if p >= 0 else s

func _strip_tags(s: String) -> String:
	var re := RegEx.create_from_string("<[^>]+>")
	var out := re.sub(s, "", true)
	return _decode_entities(out).strip_edges()

## Convertit du HTML en texte lisible : puces de liste et sauts de ligne préservés.
func _html_to_text(html: String) -> String:
	var s := html
	s = RegEx.create_from_string("(?i)<li[^>]*>").sub(s, "\n- ", true)
	s = RegEx.create_from_string("(?i)<br\\s*/?>").sub(s, "\n", true)
	s = RegEx.create_from_string("(?i)</(p|div|li|tr|h[1-6])>").sub(s, "\n", true)
	s = RegEx.create_from_string("<[^>]+>").sub(s, "", true)
	s = _decode_entities(s)
	# Normaliser : espaces multiples par ligne, lignes vides multiples réduites.
	var lines := PackedStringArray()
	for line in s.split("\n"):
		var clean := RegEx.create_from_string("[ \\t]+").sub(line.strip_edges(), " ", true)
		lines.append(clean)
	var joined := "\n".join(lines)
	joined = RegEx.create_from_string("\\n{3,}").sub(joined, "\n\n", true)
	return joined.strip_edges()

func _decode_entities(s: String) -> String:
	return s.replace("&amp;", "&").replace("&#39;", "'").replace("&nbsp;", " ") \
		.replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", "\"") \
		.replace("&rsquo;", "’").replace("&eacute;", "é").replace("&hellip;", "…")


# --------------------------------------------------------------------------
# Parsing des valeurs typées
# --------------------------------------------------------------------------

func _parse_type(s: String) -> int:
	match s.to_lower():
		"talent": return GameEnums.AbilityType.TALENT
		"exploration": return GameEnums.AbilityType.EXPLORATION
		_: return GameEnums.AbilityType.ENCOUNTER

func _parse_energy(s: String) -> int:
	match s.strip_edges().to_lower():
		"heat": return GameEnums.Energy.HEAT
		"fluid": return GameEnums.Energy.FLUID
		"crystal": return GameEnums.Energy.CRYSTAL
		"arcane": return GameEnums.Energy.ARCANE
		"toxic": return GameEnums.Energy.TOXIC
		"random": return GameEnums.Energy.RANDOM
		"variable": return GameEnums.Energy.VARIABLE
		_: return GameEnums.Energy.NONE

func _parse_cost(s: String) -> int:
	match s.strip_edges().to_lower():
		"mini": return GameEnums.Cost.MINI
		"normal": return GameEnums.Cost.NORMAL
		"medium": return GameEnums.Cost.MEDIUM
		"a lot": return GameEnums.Cost.A_LOT
		_: return GameEnums.Cost.NONE

## Extrait le premier entier entre parenthèses (« small (7) » → 7). -1 si absent.
func _parse_damage(s: String) -> int:
	var re := RegEx.create_from_string("\\((\\d+)\\)")
	var m := re.search(s)
	return int(m.get_string(1)) if m else -1

func _parse_spiricosm(s: String) -> int:
	match s.strip_edges().to_lower():
		"fiery": return GameEnums.Spiricosm.FIERY
		"wonderful": return GameEnums.Spiricosm.WONDERFUL
		_: return GameEnums.Spiricosm.GLOOM

func _split_tags(s: String) -> PackedStringArray:
	var out := PackedStringArray()
	if s.strip_edges() == "":
		return out
	for t in s.split(","):
		var v := t.strip_edges()
		if v != "":
			out.append(v)
	return out


# --------------------------------------------------------------------------
# Slugs & clés
# --------------------------------------------------------------------------

## Minuscule, accents conservés (noms d'espèces), tout le reste → underscore.
func _slugify(name: String) -> String:
	var s := name.strip_edges().to_lower().lstrip("[").rstrip("]")
	var re := RegEx.create_from_string("[^\\p{L}\\p{N}]+")
	s = re.sub(s, "_", true)
	return s.strip_edges().lstrip("_").rstrip("_")

func _species_slug_from_filename(f: String) -> String:
	var re := RegEx.create_from_string(" [0-9a-f]{32}\\.html$")
	return re.sub(f, "", true).strip_edges()

## Clé de trad en MAJUSCULE ASCII : les accents des slugs sont translittérés.
## Utilisé pour TOUTES les familles de clés (SPECIES/ABILITY/TALENT/OBJECT) afin que
## des ids accentués produisent des clés identiques côté runtime. DOIT rester identique
## à `GameEnums.key_token()` (resources/game_enums.gd), que les `name_key()`/`desc_key()`
## des Resources appellent pour retrouver ces mêmes clés via `tr()`.
func _key_token(slug: String) -> String:
	var s := slug.to_upper()
	var map := {"É": "E", "È": "E", "Ê": "E", "À": "A", "Â": "A", "Î": "I",
		"Ï": "I", "Ô": "O", "Û": "U", "Ù": "U", "Ç": "C"}
	for k in map:
		s = s.replace(k, map[k])
	return s


# --------------------------------------------------------------------------
# Traductions (.po)
# --------------------------------------------------------------------------

func _add_translation(key: String, en: String, fr: String) -> void:
	if _seen_keys.has(key):
		return
	_seen_keys[key] = true
	var fr_val := fr.strip_edges()
	var fr_todo := fr_val == ""
	_po_entries.append({
		"key": key,
		"en": en,
		"fr": en if fr_todo else fr_val,
		"fr_todo": fr_todo,
	})

func _write_po() -> void:
	_po_entries.sort_custom(func(a, b): return a["key"] < b["key"])
	_inject_block(PO_EN, _render_block(false))
	_inject_block(PO_FR, _render_block(true))

func _render_block(is_fr: bool) -> String:
	var lines := PackedStringArray()
	lines.append(GEN_START)
	for e in _po_entries:
		if is_fr and e["fr_todo"]:
			lines.append("# TODO-FR : traduction à valider")
		var value: String = e["fr"] if is_fr else e["en"]
		lines.append("msgid \"%s\"" % e["key"])
		lines.append("msgstr \"%s\"" % _po_escape(value))
		lines.append("")
	lines.append(GEN_END)
	return "\n".join(lines) + "\n"

## Remplace le bloc généré (entre marqueurs) en fin de fichier, ou l'ajoute.
func _inject_block(path: String, block: String) -> void:
	var existing := FileAccess.get_file_as_string(path)
	var start := existing.find(GEN_START)
	if start >= 0:
		existing = existing.substr(0, start).strip_edges() + "\n"
	else:
		existing = existing.strip_edges() + "\n"
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		push_warning("[gen] écriture .po impossible : %s" % path)
		return
	f.store_string(existing + "\n" + block)

func _po_escape(s: String) -> String:
	return s.replace("\\", "\\\\").replace("\"", "\\\"")
